### ISSUE TITLE
nestingLevels - when it's going to be released

### ISSUE THREAD

**Issue by arnoldsimha** [gilgaz/nested-sort#48]
I would like to know when nestingLevels option will be released.
Thank you

**Comment by hesamurai** [comment]
Hi @arnoldsimha,
I'll try my best to release it by the end of this Sunday. I hope it's not too late.
Regards

**Comment by hesamurai** [comment]
Hello again @arnoldsimha,
Version **5.0.0** is now released: https://gilgaz.com/nested-sort/v5/options
Please don't hesitate to share your ideas with us.
Regards
